variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: wordpress_tests
  MYSQL_ROOT_PASSWORD: mysql
  WITH_XDEBUG: 1
  TIMEZONE: "America/New_York"

# Select what we should cache between builds
cache:
  paths:
    - vendor/

before_script:
  # Install dependencies

  # update the docker
  - apt-get clean
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - apt-get -yqq update

  # install the required packages for the running CI tests
  # - apt-get -yqqf install zip unzip subversion mysql-client libmysqlclient-dev --fix-missing

  # PHP extensions
  - docker-php-ext-enable mbstring mcrypt mysqli pdo_mysql intl gd zip bz2

  # Set up WordPress tests
  - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql latest true

  # Install PHPCS and WPCS
  - composer global require "squizlabs/php_codesniffer=3.3.0"
  - composer global require "wp-coding-standards/wpcs=1.2.0"
  - phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs

#PHPunit:PHP5.3:MySQL:
#  image: tetraweb/php:5.3
#  services:
#    - mysql:5.6
#  script:
#    - phpcs
#    - phpunit

#PHPunit:PHP5.6:MySQL:
#  image: tetraweb/php:5.6
#  services:
#    - mysql:5.6
#  script:
#    - phpcs
#    - phpunit

PHPunit:PHP7.0:MySQL:
  image: stayallive/php:7.0
  services:
    - mysql:5.6
  script:
    - phpcs
    - phpunit

PHPunit:PHP7.1:MySQL:
  image: stayallive/php:7.1
  services:
    - mysql:5.6
  script:
    - phpcs
    - phpunit

PHPunit:PHP7.2:MySQL:
  image: stayallive/php:7.2
  services:
    - mysql:5.6
  script:
    - phpcs
    - phpunit
