variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: wordpress_tests
  MYSQL_ROOT_PASSWORD: mysql
  WITH_XDEBUG: 1
  TIMEZONE: "America/New_York"

# Select what we should cache between builds
#cache:
#  paths:
#    - vendor/

stages:
  - codestyle
  - codecoverage
  - build

before_script:
  # Install dependencies
  # update the docker
  - apt-get cleanpt-key adv --fetch-keys https://dl.yarnpkg.com/debian/pubkey.gpg
  # - curl -k -sS https://dl.yarnpkg.com/debian/pubkey.gpg > pupkey.gpg
  # - apt-key add pupkey.gpg
  - echo "deb [check-valid-until=no] http://cdn-fastly.deb.debian.org/debian jessie main" > /etc/apt/sources.list.d/jessie.list
  - echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
  - sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list
  - apt-get -yqq -o Acquire::Check-Valid-Until=false update

  # install the required packages for the running CI tests
  - apt-get -yqqf install unzip subversion rsync --fix-missing

  # Install PHPCS and WPCS
  - composer global require "squizlabs/php_codesniffer=3.3.0" --no-progress
  - composer global require "wp-coding-standards/wpcs=1.2.0" --no-progress
  - phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
  - composer global require "dealerdirect/phpcodesniffer-composer-installer=0.4.1" --no-progress

codestyle:
  tags:
    - kubernetes
    - cluster
  stage: codestyle
  image: stayallive/php:7.4
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_report"
    untracked: false
    paths:
      - build/coverage-report/
  script:
    - composer global require "phpunit/phpunit=6.*" --no-progress
    - $HOME/.composer/vendor/bin/phpunit --coverage-html build/coverage-report
    - phpcs -i
    - phpcs
    - chmod +x bin/generate-markdown-readme && bin/generate-markdown-readme

dailybrief:
  tags:
    - kubernetes
    - cluster
  stage: build
  image: stayallive/php:7.4
  retry: 2
  cache:
    untracked: true
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
      - vendor/
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    untracked: false
    paths:
      - dailybrief/
  script:
    - mkdir -p dailybrief && chmod +x bin/generate-markdown-readme
    - bin/generate-markdown-readme
    - rsync -av --exclude-from='deploy-exclude-files.txt' . dailybrief/
    - rm -rf dailybrief/dailybrief # Just to make darn sure
    - rm -rf dailybrief/build # Just to make darn sure
    - echo 'Deploying!'