variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: wordpress_tests
  MYSQL_ROOT_PASSWORD: mysql
  WITH_XDEBUG: 1
  TIMEZONE: "America/New_York"

# Select what we should cache between builds
cache:
  paths:
    - vendor/

stages:
  - codestyle
  - codecoverage
  - test
before_script:
  # Install dependencies

  # update the docker
  - apt-get clean
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - apt-get -yqq update

  # install the required packages for the running CI tests
  - apt-get -yqqf install unzip subversion mysql-client --fix-missing

  # PHP extensions
  - docker-php-ext-enable mbstring mysqli pdo_mysql intl gd zip bz2

  # Set up WordPress tests
  - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql latest true

  # Install PHPCS and WPCS
  - composer global require "phpunit/phpunit=^6"
  - composer global require "squizlabs/php_codesniffer=3.3.0"
  - composer global require "wp-coding-standards/wpcs=1.2.0"
  - phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs

codestyle:
  stage: codestyle
  image: stayallive/php:7.2
  services:
    - mysql:5.6
  script:
    - phpunit --version
    - phpcs

#PHPunit:PHP5.6:MySQL:
#  stage: test
#  image: tetraweb/php:5.6
#  services:
#    - mysql:5.6
#  script:
#    - phpunit

#PHPunit:PHP7.0:MySQL:
#  stage: test
#  image: stayallive/php:7.0
#  services:
#    - mysql:5.6
#  script:
#    - docker-php-ext-enable mcrypt
#    - phpunit

PHPunit:PHP7.1:MySQL:
  stage: test
  image: stayallive/php:7.1
  services:
    - mysql:5.6
  script:
    - docker-php-ext-enable mcrypt
    - phpunit --version
    - phpunit --coverage
    - phpunit

#PHPunit:PHP7.2:MySQL:
#  stage: test
#  image: stayallive/php:7.2
#  services:
#    - mysql:5.6
#  script:
#    - apt-get -yqq update && apt-get install -y libmcrypt-dev pkg-php-tools && pecl install mcrypt-1.0.1 && docker-php-ext-enable mcrypt
#    - phpunit
